name: calculator_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  auto_route: ^11.1.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  talker: ^5.1.12
  talker_flutter: ^5.1.12
  get_it: ^9.2.0
  freezed_annotation: ^3.1.0
  dio: ^5.9.0
  infinite_scroll_pagination: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  auto_route_generator: ^10.4.0
  flutter_lints: ^6.0.0
  freezed: ^3.2.4
  json_serializable: ^6.7.0
  intl: ^0.20.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true